<?php
/**
 * @file
 * Contains drupal hooks definitions for drupal_origins_extra module.
 */

/**
 * Implements hook_help().
 */
function drupal_origins_extra_help($path, $arg) {
  switch ($path) {
    case 'admin/help#drupal_origins_extra':
      $module_path = drupal_get_path('module', 'drupal_origins_extra');
      $output = '';
      $output .= '<h3>Drupal Origins Extra Extension</h3>';
      $output .= '<p>Drupal Origins Extra modules extension
                 (drupal_origins_extra) is a basic module which enables some
                 extra drupal modules, and their dependencies. That modules has
                 no a concrete focus, but they are very frequent at drupal
                 sites. This module doesn\'t set any additional default settings
                 during the install process.
                  </p>';
      $output .= '<p>Please, for more info and full documentation see the ';
      $output .= l(t('README.txt'), $module_path . '/README.txt');
      $output .= '</p>';

      return $output;
  }
}
