<?php
/**
 * @file
 * Contains drupal hooks definitions for Drupal Origins SEO Extension module.
 */

/**
 * Implements hook_help().
 */
function drupal_origins_seo_social_help($path, $arg) {
  switch ($path) {
    case 'admin/help#drupal_origins_seo_social':
      $module_path = drupal_get_path('module', 'drupal_origins_seo_social');
      $output = '';
      $output .= '<h3>Drupal Origins SEO & Social Extension</h3>';
      $output .= '<p>Drupal Origins SEO & Social extension
                 (drupal_origins_seo_social) is a basic module which enable some
                 basic drupal modules, and their dependencies, it is focused at
                 SEO and social networks. This module doesn\'t set an additional
                 default settings during the install process, only enable the
                 most important modules that you might use when you want improve
                 your SEO or you want add social links to your content like
                 Facebook or Twitter.</p>';
      $output .= '<p>Please, for more info and full documentation see the ';
      $output .= l(t('README.txt'), $module_path . '/README.txt');
      $output .= '</p>';

      return $output;
  }
}
