<?php
/**
 * @file
 * Contains drupal hooks definitions for Drupal Origins Search module.
 */

/**
 * Implements hook_help().
 */
function drupal_origins_search_help($path, $arg) {
  switch ($path) {
    case 'admin/help#drupal_origins_search':
      $module_path = drupal_get_path('module', 'drupal_origins_search');
      $output = '';
      $output .= '<h3>Drupal Origins Search Extension</h3>';
      $output .= '<p>Drupal Origins Search Extension (drupal_origins_search) is a
                 basic module which enables some basic drupal modules, and their
                 dependencies, it is focused at provide a search engine for Drupal
                 sites. Additionally, this module set an additional default settings
                 during the install process for be ready to start developing
                 your site.</p>';
      $output .= '<p>Please, for more info and full documentation see the ';
      $output .= l(t('README.txt'), $module_path . '/README.txt');
      $output .= '</p>';

      return $output;
  }
}
