<?php
/**
 * @file
 * Contains drupal hooks definitions for Drupal Origins Security module.
 */

/**
 * Implements hook_help().
 */
function drupal_origins_security_help($path, $arg) {
  switch ($path) {
    case 'admin/help#drupal_origins_security':
      $module_path = drupal_get_path('module', 'drupal_origins_security');
      $output = '';
      $output .= '<h3>Drupal Origins i18n Extension</h3>';
      $output .= '<p>Drupal Origins Security & Legal extension
                 (drupal_origins_security) is a basic module which enables some
                 basic drupal modules, and their dependencies, it is focused at
                 security and legal conditions. Additionally, this module set an
                 additional default settings during the install process for be
                 ready to start developing your site.</p>';
      $output .= '<p>Please, for more info and full documentation see the ';
      $output .= l(t('README.txt'), $module_path . '/README.txt');
      $output .= '</p>';

      return $output;
  }
}
